version: '3.8'
services:

  nginx:
    container_name: wp_nginx
    restart: always
    hostname: nginx
    build:
      context: .
      dockerfile: ./configs/Dockerfile.nginx
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./configs/nginx/ssl-params.conf:/etc/nginx/ssl-params.conf
      - ./configs/nginx/nginx-selfsigned.crt:/etc/nginx/nginx-selfsigned.crt
      - ./configs/nginx/nginx-selfsigned.key:/etc/nginx/nginx-selfsigned.key
      - ./configs/nginx/dhparam.pem:/etc/nginx/dhparam.pem
      - ./wordpress:/var/wordpress/
    ports:
      - "80:80"
      - "443:443"

  mysql:
    container_name: wp_mysql
    restart: always
    hostname: mysql
    build:
      context: .
      dockerfile: ./configs/Dockerfile.mysql
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - ./configs/mysql/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - ./configs/mysql/mariadb.cnf:/etc/mysql/mariadb.cnf
      - ./configs/mysql/data:/var/lib/mysql
    expose:
      - "3306"

  redis:
    container_name: wp_redis
    restart: always
    hostname: redis
    build:
      context: .
      dockerfile: ./configs/Dockerfile.redis
    expose:
      - "6379"

  wordpress:
    container_name: wordpress
    restart: always
    hostname: wordpress
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=_wp
    build:
      context: .
      dockerfile: ./configs/Dockerfile.wordpress
    volumes:
      - ./configs/php/php.ini:/etc/php/7.4/fpm/php.ini
      - ./configs/php/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
      - ./configs/php/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
      - ./wordpress:/var/wordpress/
    expose:
      - "9000"

  phpmyadmin:
    container_name: wp_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=mysql
    ports:
      - "8081:80"
